### ISSUE TITLE
añadir opcion de Tots al selector de diagnostic de las malalties de prevalença

### ISSUE THREAD

**Issue by elenagnzlz** [examba-tech/dashboard#159]

**Comment by marcfranquesa** [comment]
no existeix cap selector oi?

**Comment by marcfranquesa** [comment]
@elenagnzlz @mariarisques @BlancaUG

**Comment by elenagnzlz** [comment]
> no existeix cap selector oi?

osigui el selector es desde el bar chart de diagnostics, pero falta afegir q si no selecciones cap pues que surti Tots

**Comment by marcfranquesa** [comment]
aah, et refereixes a tots els municipis?

**Comment by elenagnzlz** [comment]
noo, a tots els diagnostics, pero ara que ho dius a tots els municipis tampoc esta

**Comment by marcfranquesa** [comment]
però, no entenc que canvia lo del tots els diagnostics

**Comment by elenagnzlz** [comment]
osigui igual que al mapa de patologies aguda si clickes fora et torna a Tots els municipis, quan clickes fora del bar chart es segueix quedant el diagnostic que ve per defecte. Pero bueno nose si cal afegirlo o sino sudem i que no hi hagi l'opcio de veure tots els diagnostics

**Comment by marcfranquesa** [comment]
ok

**Comment by marcfranquesa** [comment]
<img width="787" alt="image" src="https://github.com/examba-tech/dashboard/assets/110655741/19964360-e65d-447c-a4b8-8173b4e4a052">
No ho sé fer lo de poder tornar a seleccionar tots els diagnòsitcs, sorry, s'hauria de fer algo aquí, però no sé que és tot això.

**Comment by elenagnzlz** [comment]
sino suda, realment tampoc crec q tinguin molt interes en veure la distribucio de sexe o edats per totes les malalties a la vegada, jo crec nomes els hi interessa l'analisi de cadascuna per separat
