### ISSUE TITLE
revisad que todo funcione cuando hagáis PRs...

### ISSUE THREAD

**Issue by marcfranquesa** [examba-tech/dashboard#233]
<img width="498" alt="image" src="https://github.com/examba-tech/dashboard/assets/110655741/445296db-0742-45de-b1a9-62ebdd010c91">

creo que el error viene de los redondeos en los números?

**Comment by marcfranquesa** [comment]
<img width="709" alt="image" src="https://github.com/examba-tech/dashboard/assets/110655741/4a1c52d7-75a2-403b-bfb3-cc3946a64e69">
aparece al usar el selector de meses

**Comment by marcfranquesa** [comment]
@elenagnzlz @BlancaUG habéis redondeado los números??? quitad el redondeo de los plots y ponedlo en los cálculos que está petando

**Comment by elenagnzlz** [comment]
> <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/110655741/333807302-445296db-0742-45de-b1a9-62ebdd010c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDg5OTIsIm5iZiI6MTcxNjY0ODY5MiwicGF0aCI6Ii8xMTA2NTU3NDEvMzMzODA3MzAyLTQ0NTI5NmRiLTA3NDItNDVkZS1iMWE5LTYyZWJkZDAxMGM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNDUxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDczNDRlMjVhMDliYjk5ODZlNTIzMzM2ZDFhMzUzNTAzOTExZWQxZDA4ZTEzMmJmNzdiYzJlZGExZjkxMzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3jmZL7aA8i4FWvG14X1IV1qXtYmGmZD2iNUT1N28NBQ">
> creo que el error viene de los redondeos en los números?

es als line charts nomes?

**Comment by marcfranquesa** [comment]
no ho sé
